easy_admin:
    site_name: "Bienvenue, <b style='color:#dd0d18ef'>Gabriel</b>"
    design:
        brand_color: '#343a40'
        assets:
            favicon: '/assets/images/admin_icon.png'
    entities:
        Article:
            class: App\Entity\Article
            label: 'Articles'
            list:
                title: 'Articles publiés dans la BDD'
        Comment:
            class: App\Entity\Comment
            label: 'Commentaires'
            list:
                title: 'Commentaires enregistrés dans la BDD'
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: 'Utilisateurs enregistrés dans la BDD'
        ContactMessage:
            class: App\Entity\ContactMessage
            label: 'Mails'
            list:
                title: 'Messages reçus'
        Forum:
            class: App\Entity\Forum
            label: 'Forums'
            list:
                title: 'Forums du site'
        Thread:
            class: App\Entity\Thread
            label: 'Sujets'
            list:
                title: 'Sujets de forum'